# Generated by Django 5.2.17 on 2026-09-25 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0007_servicearea_cancel_driver_late_grace_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(editable=False, max_length=40, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'الميزات',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('name_en', models.CharField(blank=True, max_length=60)),
                ('icon', models.CharField(blank=True, help_text='اسم أيقونة Material (مثال: local_taxi). يرسمها التطبيق.', max_length=40)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'مفعّلة'), ('coming_soon', 'قريبًا'), ('hidden', 'مخفيّة')], default='active', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'خدمة',
                'verbose_name_plural': 'الخدمات',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlagAreaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to='locations.servicearea')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_overrides', to='catalog.featureflag')),
            ],
            options={
                'verbose_name': 'استثناء مدينة',
                'verbose_name_plural': 'استثناءات المدن',
                'unique_together': {('flag', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ServiceAreaOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'مفعّلة'), ('coming_soon', 'قريبًا'), ('hidden', 'مخفيّة')], max_length=20)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_overrides', to='locations.servicearea')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_overrides', to='catalog.service')),
            ],
            options={
                'verbose_name': 'استثناء مدينة',
                'verbose_name_plural': 'استثناءات المدن',
                'unique_together': {('service', 'area')},
            },
        ),
    ]
