# Generated by Django 5.2.17 on 2026-08-29 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('body', models.CharField(blank=True, max_length=300)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('normal', 'عادي'), ('low', 'منخفض')], default='normal', max_length=10)),
                ('app', models.CharField(choices=[('driver', 'تطبيق السائق'), ('customer', 'تطبيق الزبون')], default='customer', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'بالانتظار'), ('sent', 'أُرسل'), ('failed', 'فشل'), ('skipped', 'متخطّى'), ('expired', 'منتهٍ')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, max_length=120)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='unique_notification_dedupe_key')],
            },
        ),
    ]
