# Generated by Django 5.2.17 on 2026-09-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=20)),
                ('outcome', models.CharField(db_index=True, max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=300)),
                ('detail', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel', 'outcome', 'created_at'], name='notificatio_channel_8b4b48_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserChannelPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('push', 'إشعار الدفع'), ('telegram', 'تليغرام'), ('sms', 'رسالة نصّية')], db_index=True, max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='الأصغر يُجرَّب أوّلًا.')),
                ('address', models.CharField(blank=True, default='', help_text='عنوان المستخدم على هذه القناة — chat_id في تليغرام مثلًا. يبقى فارغًا للقنوات التي لا تحتاج عنوانًا.', max_length=120)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', 'channel'],
                'indexes': [models.Index(fields=['channel', 'address'], name='notificatio_channel_b3c888_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'channel'), name='unique_user_channel_preference')],
            },
        ),
    ]
