# Generated by Django 5.2.17 on 2026-09-16 11:23

import django.db.models.deletion
from django.db import migrations, models

def create_default_categories(apps, schema_editor):
    # جلب النموذج البرمجي للفئات
    VehicleCategory = apps.get_model('vehicles', 'VehicleCategory')
    # إنشاء فئة سيدان إذا لم تكن موجودة لمنع فشل قيد المفتاح الأجنبي
    VehicleCategory.objects.get_or_create(
        code='sedan', 
        defaults={
            'name': 'سيدان',
            'name_en': 'Sedan',
            'seats': 4,
            'fare_multiplier': 1.00,
            'is_active': True,
            'sort_order': 10
        }
    )

class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_servicearea_arrival_radius_m_and_more'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCategory',
            fields=[
                ('code', models.CharField(help_text='الرمز الثابت في الـAPI (حروف لاتينية صغيرة وشرطات سفلية). لا يمكن تغييره بعد الإنشاء — أخفِ الفئة بدل إعادة تسميتها.', max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='الاسم المعروض في التطبيق.', max_length=60)),
                ('name_en', models.CharField(blank=True, default='', help_text='الاسم الإنجليزي — اختياري.', max_length=60)),
                ('seats', models.PositiveSmallIntegerField(default=4, help_text='عدد الركّاب المعتاد لهذه الفئة (بلا السائق).')),
                ('fare_multiplier', models.DecimalField(decimal_places=2, default=1, help_text='معامل السعر مقارنةً بالفئة الأساسية. 1.00 يعني بلا فرق. لا يُطبَّق تلقائيًّا اليوم — محجوز لتسعير الفئات.', max_digits=4)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='إخفاء الفئة من التطبيق بلا حذفها ولا مسّ مركبات مسجَّلة.')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, help_text='ترتيب العرض في التطبيق — الأصغر أوّلًا.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas', models.ManyToManyField(blank=True, help_text='المدن التي تتوفّر فيها هذه الفئة. اتركها فارغة لتتوفّر في كلّ المدن.', related_name='vehicle_categories', to='locations.servicearea')),
            ],
            options={
                'verbose_name': 'فئة مركبة',
                'verbose_name_plural': 'فئات المركبات',
                'ordering': ['sort_order', 'code'],
            },
        ),
        # تشغيل الدالة لزرع البيانات قبل تفعيل الـ ForeignKey
        migrations.RunPython(create_default_categories),
        
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='vehicles.vehiclecategory'),
        ),
    ]
