# Generated by Django 5.2.17 on 2026-08-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rides', '0001_initial'),
        ('users', '0003_driverprofile_current_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('eta_minutes', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_offers', to='users.driverprofile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='rides.riderequest')),
            ],
            options={
                'ordering': ['eta_minutes', 'created_at'],
                'indexes': [models.Index(fields=['ride', 'status'], name='matching_ri_ride_id_7213b9_idx'), models.Index(fields=['driver', 'status'], name='matching_ri_driver__e9f6a6_idx'), models.Index(fields=['expires_at', 'status'], name='matching_ri_expires_2cb9b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('ride', 'driver'), name='unique_ride_driver_offer')],
            },
        ),
    ]
