# Generated by Django 5.2.17 on 2026-08-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rideoffer',
            options={'ordering': ['gross_fare', 'eta_minutes', 'created_at']},
        ),
    ]
