# Generated by Django 5.2.17 on 2026-08-19 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_alter_rideoffer_options'),
        ('rides', '0003_riderequest_shared_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rideoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SharedJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('scoring_strategy', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_join_request', to='rides.riderequest')),
                ('host_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_join_requests', to='matching.rideoffer')),
                ('host_ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_join_candidates', to='rides.riderequest')),
            ],
            options={
                'indexes': [models.Index(fields=['host_offer', 'status'], name='matching_sh_host_of_6761c2_idx'), models.Index(fields=['candidate_ride', 'status'], name='matching_sh_candida_39509c_idx')],
            },
        ),
    ]
