# Generated by Django 5.2.17 on 2026-08-19 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_rideoffer_status_sharedjoinrequest'),
        ('rides', '0003_riderequest_shared_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedjoinrequest',
            name='candidate_ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_join_requests', to='rides.riderequest'),
        ),
        migrations.AddConstraint(
            model_name='sharedjoinrequest',
            constraint=models.UniqueConstraint(fields=('host_offer', 'candidate_ride'), name='unique_host_offer_candidate_ride'),
        ),
    ]
