# Generated by Django 5.2.17 on 2026-08-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_alter_sharedjoinrequest_candidate_ride_and_more'),
        ('rides', '0004_remove_riderequest_shared_host'),
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedRideGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_ride_groups', to='users.driverprofile')),
                ('host_offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_group', to='matching.rideoffer')),
            ],
        ),
        migrations.CreateModel(
            name='SharedRideGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='matching.sharedridegroup')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shared_group_membership', to='rides.riderequest')),
            ],
            options={
                'indexes': [models.Index(fields=['group'], name='matching_sh_group_i_92019e_idx')],
            },
        ),
    ]
