# Generated by Django 5.2.17 on 2026-08-21 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_sharedridegroup_sharedridegroupmember'),
        ('rides', '0004_remove_riderequest_shared_host'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedridegroup',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='shared_ride_groups', to='vehicles.vehicle'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='sharedridegroupmember',
            constraint=models.UniqueConstraint(condition=models.Q(('is_host', True)), fields=('group',), name='unique_shared_group_host'),
        ),
    ]
