# Generated by Django 5.2.17 on 2026-08-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0006_sharedridegroup_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedjoinrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
    ]
