# Generated by Django 5.2.17 on 2026-08-22 13:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_alter_sharedjoinrequest_status'),
        ('rides', '0005_remove_riderequest_rides_rider_mode_47a719_idx_and_more'),
        ('users', '0004_user_gender'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledSharedTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('full', 'Full'), ('boarding', 'Boarding'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_shared_trips', to='users.driverprofile')),
                ('source_offer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_shared_trip', to='matching.rideoffer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_shared_trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledSharedTripMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_shared_trip_membership', to='rides.riderequest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='matching.scheduledsharedtrip')),
            ],
        ),
        migrations.AddIndex(
            model_name='scheduledsharedtrip',
            index=models.Index(fields=['status', 'scheduled_at'], name='matching_sc_status_6fe98d_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsharedtrip',
            index=models.Index(fields=['driver', 'status'], name='matching_sc_driver__d89453_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsharedtripmember',
            index=models.Index(fields=['trip', 'is_active'], name='matching_sc_trip_id_447929_idx'),
        ),
        migrations.AddConstraint(
            model_name='scheduledsharedtripmember',
            constraint=models.UniqueConstraint(fields=('trip', 'ride'), name='unique_scheduled_shared_trip_ride'),
        ),
    ]
