# Generated by Django 5.2.17 on 2026-08-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0008_scheduledsharedtrip_scheduledsharedtripmember_and_more'),
        ('users', '0004_user_gender'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='price_per_seat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='scheduledsharedtrip',
            name='trip_category',
            field=models.CharField(choices=[('city', 'City'), ('intercity', 'Intercity'), ('service_line', 'Service Line'), ('recreational', 'Recreational')], db_index=True, default='city', max_length=20),
        ),
        migrations.AddIndex(
            model_name='scheduledsharedtrip',
            index=models.Index(fields=['trip_category', 'status', 'scheduled_at'], name='matching_sc_trip_ca_fbb867_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledsharedtrip',
            index=models.Index(fields=['origin_city', 'destination_city'], name='matching_sc_origin__22be0e_idx'),
        ),
    ]
