# Generated by Django 5.2.17 on 2026-08-27 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_scheduledsharedtrip_description_and_more'),
        ('rides', '0010_riderequest_currency_riderequest_fare_cap_and_more'),
        ('users', '0005_driverprofile_updated_at'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('ttl_seconds', models.PositiveSmallIntegerField(default=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('approximate_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('eta_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('available_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quoted_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('counter_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pricing_policy', models.CharField(blank=True, max_length=30)),
                ('reject_reason', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_invitations', to='users.driverprofile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='rides.riderequest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_invitations', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['driver', 'status'], name='matching_ri_driver__77b02e_idx'), models.Index(fields=['ride', 'status'], name='matching_ri_ride_id_da471c_idx'), models.Index(fields=['expires_at', 'status'], name='matching_ri_expires_afaf9e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('ride',), name='unique_accepted_invitation_per_ride'), models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('ride', 'driver'), name='unique_pending_invitation_per_ride_driver')],
            },
        ),
    ]
