# Generated by Django 5.2.17 on 2026-08-26 21:04

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='رمز قصير فريد يظهر داخل area_id، مثال: JAB, LAT, DAM', max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, help_text='حدود المدينة الدقيقة (Polygon). اتركها فارغة واستخدم center + fallback_radius_km كبديل دائري مؤقت لحين توفرها.', null=True, srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('fallback_radius_km', models.DecimalField(decimal_places=2, default=15, help_text='يُستخدم فقط إذا لم تُحدَّد boundary دقيقة لهذه المدينة.', max_digits=6)),
                ('marketplace_cell_precision', models.PositiveSmallIntegerField(default=7, help_text='دقة خلايا geohash لهذه المدينة تحديدًا (عمليًا بين 5 و8).')),
                ('default_matching_radius_km', models.DecimalField(decimal_places=2, default=5, max_digits=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
