# Generated by Django 5.2.17 on 2026-08-27 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='allow_renegotiation_after_match',
            field=models.BooleanField(default=False, help_text='هل يجوز تعديل السعر بعد تثبيت السائق؟ ماليزيا تحظره صراحةً. اتركه معطّلًا ما لم يكن مسموحًا صراحةً.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='allowed_pricing_policies',
            field=models.JSONField(blank=True, default=list, help_text='خطط التسعير المسموح بها في هذه المنطقة. يمكن اختيار أكثر من واحدة. اختر ما يوافق قانون البلد فعلًا.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='commission_cap_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سقف عمولة المنصة. مثال: 15 (إندونيسيا)، 18 (كينيا). MVP=0.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='compliance_note',
            field=models.TextField(blank=True, help_text='ملاحظات المراجعة القانونية. إن كان الوضع التنظيمي غامضًا (قطر/الكويت/سوريا) سجّل ذلك هنا صراحةً - الصمت ليس إذنًا.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO 3166-1 alpha-2، مثال: SY, JO, AE. للتقارير والامتثال.', max_length=2),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='currency_code',
            field=models.CharField(default='SYP', help_text='ISO 4217. كل المبالغ في هذه المنطقة بهذه العملة.', max_length=3),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='default_pricing_policy',
            field=models.CharField(choices=[('platform_fixed', 'سعر المنصة الثابت (أوبر/كريم)'), ('regulated_tariff', 'تعرفة رسمية إلزامية (الأردن/دبي)'), ('tariff_corridor', 'ممر تعرفة: أرضية وسقف (الهند/إندونيسيا)'), ('driver_bidding', 'مزايدة السائقين (السائق يقترح سعره)'), ('customer_bidding', 'الزبون يقترح السعر (نموذج inDrive)')], default='platform_fixed', help_text='الخطة المطبَّقة تلقائيًا. يجب أن تكون ضمن المسموح بها.', max_length=30),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='driver_min_share_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أقل نسبة يجب أن يقبضها السائق من الأجرة. مثال: 80 (الهند).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='fare_cap_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سقف السعر كنسبة من تسعيرة المنصة. مثال: 2.00 (الهند).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='fare_floor_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أرضية السعر كنسبة من تسعيرة المنصة. مطلوبة مع ممر التعرفة. مثال: 0.50 (الهند)، 0.93 (ألمانيا: حد أدنى لحماية التاكسي).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='invitation_allowed_modes',
            field=models.JSONField(blank=True, default=list, help_text='أنماط الخدمة التي تُفعَّل فيها الخريطة الحيّة والدعوة المباشرة. مثال: ["fast", "express"] أو أضف "shared" لتفعيل المشتركة.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='invitation_max_parallel',
            field=models.PositiveSmallIntegerField(default=1, help_text='كم دعوة يمكن للزبون إرسالها في وقت واحد للطلب نفسه. 1 = سيارة واحدة ثم انتظار (الموصى به وما تنص عليه الوثيقة).'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='invitation_ttl_default',
            field=models.PositiveSmallIntegerField(default=20, help_text='المهلة المختارة مسبقًا. يجب أن تكون ضمن القائمة أعلاه.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='invitation_ttl_options',
            field=models.JSONField(blank=True, default=list, help_text='المهل (بالثواني) التي تُعرض على الزبون ليختار منها قبل إرسال الدعوة. مثال: [20, 40, 60]. القيمة خارج القائمة تُرفض من الخادم.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='legal_reference',
            field=models.CharField(blank=True, help_text='رقم القانون/اللائحة التي بُنيت عليها الإعدادات أعلاه.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='min_fare_absolute',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='حد أدنى مطلق للأجرة بعملة المنطقة. مثال: 13 درهم في دبي.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='price_change_workflow',
            field=models.CharField(choices=[('none', 'بلا إجراء'), ('notify', 'إخطار مسبق للجهة المنظِّمة (مصر)'), ('approval', 'موافقة مسبقة قبل التفعيل (السعودية)')], default='none', help_text="الفرق تشغيلي جوهري: 'إخطار' يسجّل التغيير ويمضي، 'موافقة' يحجب التفعيل حتى ردّ الجهة.", max_length=20),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='regulator_name',
            field=models.CharField(blank=True, help_text='مثال: هيئة تنظيم النقل البري (LTRC) — الأردن', max_length=150),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='shared_destination_precision',
            field=models.PositiveSmallIntegerField(choices=[(4, '~20 كم — حماية قصوى (كثافة منخفضة/ريف)'), (5, '~5 كم — متوازن (الافتراضي)'), (6, '~1.2 كم — فلترة دقيقة (مدن مزدحمة)')], default=5, help_text='كم نُقرِّب وجهة الركّاب الحاليين عند عرض سيارة مشتركة لمرشّح انضمام. كلما زادت الدقّة تحسّنت الفلترة وقلّت الخصوصية.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='shared_min_compatibility_score',
            field=models.PositiveSmallIntegerField(default=55, help_text='أقل درجة توافق (من 100) تُظهر سيارة مشتركة كخيار صالح. أقل = مطابقات أكثر وانعراج أكبر.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='surge_max_multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='مطلوب مع surge_mode=capped. مثال: 2.00 (الهند)، 1.75 (مدريد).', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='surge_mode',
            field=models.CharField(choices=[('disabled', 'معطّل'), ('capped', 'خوارزمي بسقف أقصى'), ('regulator_tiers', 'نوافذ ورسوم تحددها الهيئة (دبي)'), ('free', 'خوارزمي بلا سقف')], default='disabled', help_text="تنبيه: 'مسموح بالتسعير الديناميكي' و'المنصة تحسبه' شيئان مختلفان. دبي تسمح بالتغيّر لكن الهيئة هي من تحدد النوافذ والرسوم → اختر regulator_tiers لا capped.", max_length=20),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='marketplace_cell_precision',
            field=models.PositiveSmallIntegerField(default=7, help_text='دقة خلايا geohash لهذه المدينة (عمليًا 5–8). 5≈4.9كم · 6≈1.2كم · 7≈150م · 8≈38م'),
        ),
    ]
