# Generated by Django 5.2.17 on 2026-09-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_servicearea_allow_renegotiation_after_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='arrival_radius_m',
            field=models.PositiveSmallIntegerField(blank=True, help_text='كم مترًا يُقبل بينها وبين نقطة الالتقاء لتسجيل «وصلت». مدينة بأزقّة ضيّقة تحتاج رقمًا أكبر. فارغ = 200 متر.', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='average_speed_kmh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='السرعة الوسطية الفعلية بما فيها التوقّف والإشارات — لا الحدّ الأقصى المسموح. 30 كم/سا نقطة بداية معقولة.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='dropoff_radius_m',
            field=models.PositiveSmallIntegerField(blank=True, help_text='كم مترًا يُقبل بينها وبين الوجهة لإنهاء الرحلة بلا تعليم للمراجعة. فارغ = 300 متر.', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='invitation_reject_cooldown_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='بعد رفض سائق لزبون، كم يبقى مخفيًّا عنه. فارغ = الافتراضي العامّ.', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='location_max_age_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='أقصى عمر لموقع السائق في القاعدة ليدخل المطابقة. فارغ = الافتراضي العامّ (MATCHING_LOCATION_MAX_AGE_SECONDS).', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='marketplace_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نصف قطر الطلبات المجدولة والرحلات المنشورة (كم). أوسع من الفوري عمدًا: مَن يحجز لغدٍ يقبل سائقًا أبعد. فارغ = الافتراضي العامّ.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='offer_ttl_seconds',
            field=models.PositiveIntegerField(blank=True, help_text='مهلة صلاحية عرض السائق قبل انتهائه تلقائيًّا. فارغ = الافتراضي العامّ (RIDE_OFFER_TTL_SECONDS).', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='presence_fresh_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='أقصى عمر للنبض ليُعدّ السائق حاضرًا لا متأخّرًا. يجب أن يكون أصغر من مهلة الانقطاع. فارغ = 30 ثانية.', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='presence_stale_seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='انقطاع نبض السائق هذه المدّة يُخرجه من الأسطول المرئي. خفضه يُنقّي الخريطة ويقسو على الشبكات الضعيفة. فارغ = 60 ثانية.', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='ride_search_window_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='كم يبقى الطلب الفوري يبحث عن سائق قبل أن ينتهي. لا يُطبَّق على الطلبات المجدولة. فارغ = 10 دقائق.', null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='road_detour_factor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نسبة مسافة الطريق إلى المسافة الهوائية. 1.35 نقطة بداية معقولة لمدينة ساحلية. اتركه فارغًا لاستخدام الافتراضي العام.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='shared_join_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='أقصى مسافة بين نقطتَي التقاط في المشاركة الفورية (كم). رفعه يزيد المطابقات ويزيد انعراج الراكب الأوّل. فارغ = 3 كم.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='shared_scheduled_dest_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نطاق توافق الوجهة في المشاركة المجدولة (كم). فارغ = 15 كم.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='shared_scheduled_pickup_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='نطاق التقاط المشاركة المجدولة (كم). فارغ = 10 كم.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='shared_scheduled_time_window_minutes',
            field=models.PositiveSmallIntegerField(blank=True, help_text='فرق الوقت المقبول بين رحلتين مجدولتين لتُعدّا متوافقتين (دقيقة). فارغ = 60 دقيقة.', null=True),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='default_matching_radius_km',
            field=models.DecimalField(decimal_places=2, default=5, help_text='نصف قطر البحث للطلبات الفورية (كم). هذا هو الرقم الذي يحدّد مَن يُطابَق فعلًا ومَن يظهر على خريطة الزبون.', max_digits=6),
        ),
    ]
