# Generated by Django 5.2.17 on 2026-09-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_servicearea_arrival_radius_m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='first_ride_discount_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='سقف الخصم بالعملة المحلّية (الخطّة: سقفٌ لا نسبة). فارغ = بلا سقف.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='first_ride_discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='نسبة خصم أوّل مشوار للزبون الجديد. 0 = معطَّل. مثال: 50.', max_digits=5),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='referral_reward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='رصيدٌ يُمنح للداعي والمدعوّ معًا بعد أوّل رحلة مكتملة للمدعوّ. 0 = معطَّل.', max_digits=12),
        ),
    ]
