# Generated by Django 5.2.17 on 2026-09-21 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='marketplace_cell_precision',
            field=models.PositiveSmallIntegerField(default=5, help_text='دقة خلايا geohash لهذه المدينة (عمليًا 5–8). 5≈4.9كم · 6≈1.2كم · 7≈150م · 8≈38م. الزبون لا يرى إلّا سائقي خليّته: بدقّة 7 كان سائقٌ على بُعد كيلومتر لا يظهر على الخريطة (وُجد بجهازين حقيقيّين في 2026-09-21)، فالافتراض 5 ليوافق نصف قطر المطابقة (5 كم).'),
        ),
    ]
