# Generated by Django 5.2.17 on 2026-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_marketplace_cell_precision_5'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='auto_dispatch_max_attempts',
            field=models.PositiveSmallIntegerField(default=5, help_text='«الأقرب»: كم سائقًا يُجرَّب بالتتابع قبل أن يُترك الطلب لعروض السائقين العاديّة.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='auto_dispatch_ttl_seconds',
            field=models.PositiveSmallIntegerField(default=15, help_text='«الأقرب»: كم ثانية ينتظر النظام ردّ السائق قبل أن ينتقل تلقائيًّا إلى السائق التالي.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='search_radius_options_km',
            field=models.JSONField(blank=True, default=list, help_text='أنصاف الأقطار (كم) التي يختار منها الزبون نطاق البحث. مثال: [1, 3, 5, 10]. فارغ = لا اختيار، ويُستعمل نصف قطر المنطقة. القيم الأكبر من نصف قطر الطلب الفوري تُقصّ إليه.'),
        ),
    ]
