# Generated by Django 5.2.17 on 2026-09-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_servicearea_auto_dispatch_max_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicearea',
            name='cancel_driver_late_grace_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='إن تأخّر السائق عن وقت وصوله المعلن بأكثر من هذه الدقائق، فإلغاء الزبون مجّانيّ مهما مضى من وقت.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='cancel_free_window_seconds',
            field=models.PositiveIntegerField(default=120, help_text='إلغاء الزبون مجّانيّ خلال هذه الثواني بعد تثبيت السائق.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='cancel_wait_minutes',
            field=models.PositiveSmallIntegerField(default=5, help_text='إلغاءٌ بعد أن وصل السائق وانتظر هذه الدقائق يُحسب مخالفتين: السائق خسر المشوار والوقت معًا.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='driver_cancel_block_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='مدّة إيقاف السائق عن العروض والدعوات بعد تجاوز الحدّ.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='driver_cancel_daily_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='كم مرّة يلغي السائق بعد القبول في اليوم قبل إيقافه مؤقّتًا. 0 = بلا حدّ.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='late_cancel_penalty_hours',
            field=models.PositiveSmallIntegerField(default=24, help_text='مدّة العقوبة: الزبون يطلب بالعروض وحدها («الأقرب» و«اختر سيارتك» تتوقّفان)، ويرى السائقون شارةً على طلبه.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='late_cancel_strike_limit',
            field=models.PositiveSmallIntegerField(default=3, help_text='عدد مخالفات الإلغاء المتأخّر التي تُطلق العقوبة. 0 = بلا عقوبة.'),
        ),
        migrations.AddField(
            model_name='servicearea',
            name='late_cancel_window_days',
            field=models.PositiveSmallIntegerField(default=7, help_text='المخالفات تُعدّ ضمن هذه الأيّام الأخيرة فقط.'),
        ),
    ]
