# Generated by Django 5.2.17 on 2026-09-25 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_servicearea_cancel_driver_late_grace_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicearea",
            name="wasted_trip_compensation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="تعويض السائق عن المشوار الفاضي بعملة المنطقة. فارغ = أجرة فتح العدّاد لطلب الزبون نفسه. 0 = بلا تعويض.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="wasted_trip_compensation_daily_cap",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="أقصى عدد تعويضات للسائق في اليوم — حمايةٌ من سائقٍ وزبونٍ يتّفقان على «لم يحضر» ليأخذا التعويض.",
            ),
        ),
    ]
