# Generated by Django 5.2.17 on 2026-09-25 23:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0008_servicearea_wasted_trip_compensation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicearea",
            name="customer_proposal_counter_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.50"),
                help_text="أعلى عرض يقدّمه السائق كنسبة من سعر الزبون (1.50 = +50٪).",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="customer_proposal_min_ratio",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.70"),
                help_text="أدنى سعر يقترحه الزبون كنسبة من تسعيرة المنصّة (0.70 = 70٪). يمنع سباقًا نحو الأرخص على حساب السائق.",
                max_digits=4,
            ),
        ),
        migrations.AddField(
            model_name="servicearea",
            name="customer_proposal_step",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("500"),
                help_text="خطوة زرّي − و+ في شاشة الزبون، بعملة المنطقة.",
                max_digits=12,
            ),
        ),
    ]
