# Generated by Django 5.2.17 on 2026-08-28 20:23

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0010_rideinvitation'),
        ('rides', '0010_riderequest_currency_riderequest_fare_cap_and_more'),
        ('users', '0005_driverprofile_updated_at'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'Created'), ('driver_arriving', 'Driver Arriving'), ('driver_arrived', 'Driver Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], db_index=True, default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('arriving_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('gps_points_count', models.PositiveIntegerField(default=0)),
                ('final_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('pickup_verified', models.BooleanField(default=False)),
                ('dropoff_verified', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('review_reason', models.CharField(blank=True, max_length=255)),
                ('cancelled_by', models.CharField(blank=True, max_length=20)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='users.driverprofile')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='matching.rideoffer')),
                ('ride', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='trip', to='rides.riderequest')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripCompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('pickup_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('dropoff_point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('final_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('gps_start_verified', models.BooleanField(default=False)),
                ('gps_arrival_verified', models.BooleanField(default=False)),
                ('gps_end_verified', models.BooleanField(default=False)),
                ('gps_points_count', models.PositiveIntegerField(default=0)),
                ('completion_source', models.CharField(choices=[('driver_app', 'تطبيق السائق'), ('admin', 'الإدارة'), ('auto', 'إنهاء تلقائي')], default='driver_app', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='completion_record', to='trips.trip')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='TripLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('heading', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='trips.trip')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', 'status'], name='trips_trip_driver__692693_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['customer', '-created_at'], name='trips_trip_custome_fc8741_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', 'created_at'], name='trips_trip_status_4e1bc3_idx'),
        ),
        migrations.AddIndex(
            model_name='triplocation',
            index=models.Index(fields=['trip', 'timestamp'], name='trips_tripl_trip_id_25e17b_idx'),
        ),
    ]
