# Generated by Django 5.2.17 on 2026-09-25 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_riderequest_auto_dispatch_and_more'),
        ('trips', '0001_initial'),
        ('users', '0009_backfill_referral_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=10)),
                ('kind', models.CharField(choices=[('free', 'مجّانيّ'), ('driver_late', 'السائق تأخّر'), ('late', 'متأخّر'), ('after_wait', 'بعد انتظار السائق'), ('driver', 'ألغاه السائق')], max_length=20)),
                ('strikes', models.PositiveSmallIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_cancellations', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ride_cancellations', to='users.driverprofile')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='rides.riderequest')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellations', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'created_at'], name='trips_cance_custome_33f83c_idx'), models.Index(fields=['driver', 'created_at'], name='trips_cance_driver__cd7f3b_idx')],
            },
        ),
    ]
