# Generated by Django 5.2.17 on 2026-09-25 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_cancellationrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellationrecord",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("changed_mind", "غيّرت رأيي"),
                    ("driver_late", "السائق تأخّر"),
                    ("driver_not_moving", "السائق لا يتحرّك نحوي"),
                    ("driver_asked", "السائق طلب منّي الإلغاء"),
                    ("found_other", "وجدت وسيلة أخرى"),
                    ("wrong_pickup", "مكان الالتقاط خطأ"),
                    ("other", "سبب آخر"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
