# Generated by Django 5.2.17 on 2026-09-25 23:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_cancellationrecord_reason_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="cancellationrecord",
            name="driver_compensation",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="cancellationrecord",
            name="kind",
            field=models.CharField(
                choices=[
                    ("free", "مجّانيّ"),
                    ("driver_late", "السائق تأخّر"),
                    ("late", "متأخّر"),
                    ("after_wait", "بعد انتظار السائق"),
                    ("driver", "ألغاه السائق"),
                    ("no_show", "الزبون لم يحضر"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cancellationrecord",
            name="reason_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("changed_mind", "غيّرت رأيي"),
                    ("driver_late", "السائق تأخّر"),
                    ("driver_not_moving", "السائق لا يتحرّك نحوي"),
                    ("driver_asked", "السائق طلب منّي الإلغاء"),
                    ("found_other", "وجدت وسيلة أخرى"),
                    ("wrong_pickup", "مكان الالتقاط خطأ"),
                    ("other", "سبب آخر"),
                    ("customer_no_show", "الزبون لم يحضر"),
                    ("car_problem", "عطل بالسيارة"),
                    ("customer_unreachable", "الزبون لا يردّ"),
                    ("road_blocked", "المكان بعيد أو الطريق مغلق"),
                    ("other", "سبب آخر"),
                ],
                default="",
                max_length=24,
            ),
        ),
    ]
