# Generated by Django 5.2.17 on 2026-08-30 21:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
        ('users', '0005_driverprofile_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='إجمالي ما على الزبون. يقابل customer_total في الطلب.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='عمولة المنصّة من هذا المبلغ.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('driver_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='صافي استحقاق السائق = amount - platform_fee.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('amount_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('gateway_code', models.CharField(db_index=True, help_text='رمز البوابة كما هو معرَّف في payments/gateways/.', max_length=40)),
                ('gateway_reference', models.CharField(blank=True, db_index=True, help_text='معرّف العملية لدى المزوّد. فارغ للنقدي.', max_length=255)),
                ('gateway_payload', models.JSONField(blank=True, default=dict, help_text='أي بيانات إضافية يحتاجها المزوّد. لا مخطّط ثابت عمدًا.')),
                ('status', models.CharField(choices=[('pending', 'بانتظار التحصيل'), ('processing', 'قيد المعالجة لدى المزوّد'), ('authorized', 'محجوز ولم يُحصَّل'), ('paid', 'محصَّل'), ('partially_refunded', 'مُعاد جزئيًا'), ('refunded', 'مُعاد بالكامل'), ('failed', 'فشل نهائي'), ('cancelled', 'ملغى')], db_index=True, default='pending', max_length=24)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='users.driverprofile')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('customer', 'الزبون'), ('driver', 'السائق — تسوية مع المنصّة'), ('driver_cash', 'السائق — نقد بيده'), ('platform', 'المنصّة'), ('gateway', 'بوابة الدفع')], db_index=True, max_length=20)),
                ('account_ref', models.CharField(blank=True, db_index=True, help_text='معرّف صاحب الحساب: رقم المستخدم أو السائق. فارغ للمنصّة.', max_length=64)),
                ('direction', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('entry_type', models.CharField(choices=[('trip_fare', 'أجرة رحلة'), ('platform_commission', 'عمولة المنصّة'), ('driver_earning', 'استحقاق السائق'), ('refund', 'إعادة مبلغ'), ('settlement', 'تسوية'), ('adjustment', 'تسوية يدوية')], db_index=True, max_length=30)),
                ('transaction_ref', models.CharField(db_index=True, max_length=64)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway_code', models.CharField(max_length=40)),
                ('action', models.CharField(choices=[('charge', 'تحصيل'), ('capture', 'تثبيت الحجز'), ('refund', 'إعادة'), ('webhook', 'إشعار وارد'), ('cancel', 'إلغاء')], max_length=20)),
                ('ok', models.BooleanField(default=False)),
                ('permanent_failure', models.BooleanField(default=False, help_text='فشل لا تُجدي إعادة المحاولة معه.')),
                ('error', models.CharField(blank=True, max_length=300)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('reason', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'قيد التنفيذ'), ('completed', 'منفَّذ'), ('failed', 'فشل')], db_index=True, default='pending', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.payment')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('net_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='موجب: للسائق عند المنصّة. سالب: على السائق للمنصّة.', max_digits=14)),
                ('lifetime_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('lifetime_commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='users.driverprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['driver', 'currency'], name='payments_dr_driver__f7461d_idx')],
                'constraints': [models.UniqueConstraint(fields=('driver', 'currency'), name='unique_driver_balance_per_currency')],
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='payments_pa_status_343680_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['driver', 'status'], name='payments_pa_driver__49a96d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['customer', '-created_at'], name='payments_pa_custome_a935a8_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['gateway_code', 'status'], name='payments_pa_gateway_2a9b32_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', Decimal('0'))), name='payment_amount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_refunded__lte', models.F('amount'))), name='payment_refund_not_exceeding_amount'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'account_ref', '-created_at'], name='payments_le_account_3c0efc_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction_ref'], name='payments_le_transac_0d6bf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', Decimal('0'))), name='ledger_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['payment', '-created_at'], name='payments_pa_payment_7898ee_idx'),
        ),
    ]
