# Generated by Django 5.2.17 on 2026-09-20 06:36

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='entry_type',
            field=models.CharField(choices=[('trip_fare', 'أجرة رحلة'), ('platform_commission', 'عمولة المنصّة'), ('driver_earning', 'استحقاق السائق'), ('refund', 'إعادة مبلغ'), ('settlement', 'تسوية'), ('adjustment', 'تسوية يدوية'), ('promotion', 'خصم ترويجي تتحمّله المنصّة')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='driver_net',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='صافي استحقاق السائق = الأجرة المتّفق عليها - platform_fee.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.CreateModel(
            name='CustomerCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('reason', models.CharField(choices=[('referral_referrer', 'دعا زبونًا أتمّ رحلته الأولى'), ('referral_referee', 'أتمّ رحلته الأولى بدعوة'), ('manual', 'منح يدويّ')], max_length=32)),
                ('consumed_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumed_credits', to='payments.payment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to=settings.AUTH_USER_MODEL)),
                ('source_payment', models.ForeignKey(blank=True, help_text='الدفعة التي استحقّت المكافأة (رحلة المدعوّ الأولى).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_credits', to='payments.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
