# Generated by Django 5.2.17 on 2026-09-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_promotions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercredit',
            name='reason',
            field=models.CharField(choices=[('referral_referrer', 'دعا زبونًا أتمّ رحلته الأولى'), ('referral_referee', 'أتمّ رحلته الأولى بدعوة'), ('manual', 'منح يدويّ'), ('campaign', 'عرض من الإدارة')], max_length=32),
        ),
    ]
