# Generated by Django 5.2.17 on 2026-09-25 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_customercredit_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgerentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("trip_fare", "أجرة رحلة"),
                    ("platform_commission", "عمولة المنصّة"),
                    ("driver_earning", "استحقاق السائق"),
                    ("refund", "إعادة مبلغ"),
                    ("settlement", "تسوية"),
                    ("adjustment", "تسوية يدوية"),
                    ("promotion", "خصم ترويجي تتحمّله المنصّة"),
                    ("compensation", "تعويض مشوار فاضي تتحمّله المنصّة"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="ledgerentry",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ledger_entries",
                to="payments.payment",
            ),
        ),
    ]
