# Generated by Django 5.2.17 on 2026-08-18 13:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('mode', models.CharField(choices=[('fast', 'Fast'), ('express', 'Express'), ('standard', 'Standard'), ('saving', 'Saving'), ('shared', 'Shared'), ('scheduled', 'Scheduled')], max_length=20)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('searching', 'Searching'), ('matched', 'Matched'), ('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='searching', max_length=30)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('time_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_fare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ride_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='rides_rider_custome_0c5248_idx'), models.Index(fields=['status', 'created_at'], name='rides_rider_status_3e479f_idx'), models.Index(fields=['mode', 'status'], name='rides_rider_mode_47a719_idx')],
            },
        ),
    ]
