# Generated by Django 5.2.17 on 2026-08-19 11:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('van', 'Van')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('searching', 'Searching'), ('offers_received', 'Offers Received'), ('driver_selected', 'Driver Selected'), ('driver_arriving', 'Driver Arriving'), ('driver_arrived', 'Driver Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='searching', max_length=30),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['requested_vehicle_type', 'status'], name='rides_rider_request_ffcaab_idx'),
        ),
    ]
