# Generated by Django 5.2.17 on 2026-08-19 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderequest_requested_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='shared_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_members', to='rides.riderequest'),
        ),
    ]
