# Generated by Django 5.2.17 on 2026-08-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_riderequest_shared_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='shared_host',
        ),
    ]
