# Generated by Django 5.2.17 on 2026-08-22 13:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_remove_riderequest_shared_host'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riderequest',
            name='rides_rider_mode_47a719_idx',
        ),
        migrations.AddField(
            model_name='riderequest',
            name='booking_type',
            field=models.CharField(choices=[('instant', 'Instant'), ('scheduled', 'Scheduled')], db_index=True, default='instant', max_length=20),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='service_type',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='mode',
            field=models.CharField(choices=[('fast', 'Fast'), ('express', 'Express'), ('standard', 'Standard'), ('saving', 'Saving')], db_index=True, default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['service_type', 'status'], name='rides_rider_service_43ef0e_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['booking_type', 'status'], name='rides_rider_booking_5e906e_idx'),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['scheduled_at', 'status'], name='rides_rider_schedul_6460d1_idx'),
        ),
    ]
