# Generated by Django 5.2.17 on 2026-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_remove_riderequest_rides_rider_mode_47a719_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='route_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='route_duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='route_geometry',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
