# Generated by Django 5.2.17 on 2026-08-22 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0006_riderequest_route_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='riderequest',
            name='rides_rider_service_43ef0e_idx',
        ),
        migrations.RemoveIndex(
            model_name='riderequest',
            name='rides_rider_booking_5e906e_idx',
        ),
        migrations.RemoveIndex(
            model_name='riderequest',
            name='rides_rider_schedul_6460d1_idx',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='booking_type',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='service_type',
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='mode',
            field=models.CharField(choices=[('fast', 'Fast'), ('express', 'Express'), ('standard', 'Standard'), ('saving', 'Saving'), ('shared', 'Shared'), ('scheduled', 'Scheduled')], max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['mode', 'status'], name='rides_rider_mode_47a719_idx'),
        ),
    ]
