# Generated by Django 5.2.17 on 2026-08-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_remove_riderequest_rides_rider_service_43ef0e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='mode',
            field=models.CharField(choices=[('fast', 'Fast'), ('express', 'Express'), ('standard', 'Standard'), ('saving', 'Saving'), ('shared', 'Shared')], max_length=20),
        ),
    ]
