# Generated by Django 5.2.17 on 2026-08-22 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0009_scheduledsharedtrip_description_and_more'),
        ('rides', '0008_alter_riderequest_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='destination_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='origin_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='published_trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_bookings', to='matching.scheduledsharedtrip'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='trip_category',
            field=models.CharField(choices=[('city', 'City Ride'), ('intercity', 'Intercity Trip'), ('service_line', 'Service Line'), ('recreational', 'Recreational Trip')], db_index=True, default='city', max_length=20),
        ),
        migrations.AddIndex(
            model_name='riderequest',
            index=models.Index(fields=['trip_category', 'status'], name='rides_rider_trip_ca_9ae616_idx'),
        ),
    ]
