# Generated by Django 5.2.17 on 2026-08-27 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_servicearea_allow_renegotiation_after_match_and_more'),
        ('rides', '0009_riderequest_destination_city_riderequest_origin_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='currency',
            field=models.CharField(default='SYP', max_length=3),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='fare_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='fare_floor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='pricing_policy',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='service_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='locations.servicearea'),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='surge_multiplier',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4),
        ),
    ]
