# Generated by Django 5.2.17 on 2026-09-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0010_riderequest_currency_riderequest_fare_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='route_source',
            field=models.CharField(blank=True, db_index=True, default='', help_text='provider | estimated', max_length=20),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='requested_vehicle_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
