# Generated by Django 5.2.17 on 2026-09-20 06:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_riderequest_route_source_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RideSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='مثال: «إلى الجامعة».', max_length=60)),
                ('pickup', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('departure_time', models.TimeField(help_text='وقت الانطلاق بالتوقيت المحلّي للمدينة.')),
                ('weekdays', models.JSONField(default=list)),
                ('mode', models.CharField(default='standard', max_length=20)),
                ('passenger_count', models.PositiveSmallIntegerField(default=1)),
                ('requested_vehicle_type', models.CharField(blank=True, max_length=20, null=True)),
                ('lead_minutes', models.PositiveSmallIntegerField(default=30, help_text='قبل الموعد بكم دقيقة يُنشأ الطلب ويُعرض على السائقين.')),
                ('is_active', models.BooleanField(default=True)),
                ('last_materialized_on', models.DateField(blank=True, help_text='آخر يومٍ أُنشئ له طلب — يمنع التكرار.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['departure_time', 'id'],
            },
        ),
        migrations.AddField(
            model_name='riderequest',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='rides.ridesubscription'),
        ),
    ]
