# Generated by Django 5.2.17 on 2026-09-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_ridesubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='auto_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderequest',
            name='search_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
