# Generated by Django 5.2.17 on 2026-09-25 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rides", "0013_riderequest_auto_dispatch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="riderequest",
            name="customer_proposed_fare",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
