# Generated by Django 5.2.17 on 2026-09-25 03:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0007_servicearea_cancel_driver_late_grace_minutes_and_more'),
        ('payments', '0003_alter_customercredit_reason'),
        ('users', '0009_backfill_referral_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drivers', models.ManyToManyField(blank=True, related_name='growth_groups', to='users.driverprofile')),
            ],
            options={
                'verbose_name': 'مجموعة سائقين',
                'verbose_name_plural': 'مجموعات السائقين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('scope', models.CharField(choices=[('driver', 'سائق بعينه'), ('group', 'مجموعة سائقين'), ('area', 'مدينة'), ('default', 'عامّة')], max_length=10)),
                ('rate_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='نسبة من الأجرة (0–50).', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('50'))])),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ ثابت يُضاف على كلّ رحلة.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('min_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, help_text='اختياريّ مع السائق/المجموعة: يقصر القاعدة على مدينة.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='locations.servicearea')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='users.driverprofile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='growth.drivergroup')),
            ],
            options={
                'verbose_name': 'قاعدة عمولة',
                'verbose_name_plural': 'قواعد العمولة',
                'ordering': ['-is_active', 'scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان الإشعار.', max_length=80)),
                ('body', models.CharField(help_text='نصّ الإشعار.', max_length=240)),
                ('audience', models.CharField(choices=[('all_customers', 'كلّ الزبائن'), ('idle_customers', 'الزبائن الخاملون'), ('new_customers', 'زبائن سجّلوا ولم يركبوا'), ('top_customers', 'أنشط الزبائن'), ('all_drivers', 'كلّ السائقين'), ('idle_drivers', 'السائقون الخاملون'), ('top_drivers', 'أنشط السائقين'), ('driver_group', 'مجموعة سائقين')], max_length=20)),
                ('idle_days', models.PositiveSmallIntegerField(default=14, help_text='للخاملين: بلا رحلة منذ هذه الأيّام.')),
                ('top_count', models.PositiveSmallIntegerField(default=50, help_text='للأنشط: كم مستخدمًا.')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='للزبائن: رصيد يُخصم من الرحلة التالية. صفر = رسالة فقط.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('currency', models.CharField(default='SYP', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'مسوّدة'), ('sent', 'أُرسل')], default='draft', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, help_text='فارغ = كلّ المدن.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.servicearea')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='growth.drivergroup')),
            ],
            options={
                'verbose_name': 'عرض/حملة',
                'verbose_name_plural': 'العروض والحملات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncentiveProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(choices=[('day', 'يوميّ'), ('week', 'أسبوعيّ'), ('month', 'شهريّ')], default='week', max_length=10)),
                ('target_trips', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('min_rating', models.DecimalField(blank=True, decimal_places=2, help_text='اختياريّ: لا مكافأة تحت هذا التقييم.', max_digits=3, null=True)),
                ('reward_kind', models.CharField(choices=[('fuel_liters', 'ليترات وقود'), ('other', 'مكافأة أخرى (يُسلّمها المشغّل)')], default='fuel_liters', max_length=20)),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reward_label', models.CharField(blank=True, help_text='كيف تظهر المكافأة للسائق: «10 ليترات بنزين».', max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.servicearea')),
                ('group', models.ForeignKey(blank=True, help_text='فارغ = كلّ السائقين.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='growth.drivergroup')),
            ],
            options={
                'verbose_name': 'برنامج حوافز',
                'verbose_name_plural': 'برامج الحوافز',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='growth.campaign')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='payments.customercredit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('campaign', 'user')},
            },
        ),
        migrations.CreateModel(
            name='IncentiveAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('trips_completed', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'بانتظار التسليم'), ('delivered', 'سُلّمت')], default='pending', max_length=10)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentive_awards', to='users.driverprofile')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='awards', to='growth.incentiveprogram')),
            ],
            options={
                'verbose_name': 'مكافأة مستحقّة',
                'verbose_name_plural': 'المكافآت المستحقّة',
                'ordering': ['-created_at'],
                'unique_together': {('program', 'driver', 'period_start')},
            },
        ),
    ]
