# Generated by Django 5.2.17 on 2026-09-25 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commissionrule",
            name="hour_from",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="بداية النافذة بتوقيت دمشق (0–23). مع «حتّى» فقط.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(23)],
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="hour_to",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="نهاية النافذة (غير مشمولة). 22 ← 5 = الليل عبر منتصفه.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(24)],
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="service_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text="رمز الخدمة من الكتالوج (taxi، shared، intercity…). فارغ = كلّ الخدمات.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="commissionrule",
            name="weekdays",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="أيّام الأسبوع بأرقام: 0=الاثنين … 4=الجمعة، 5=السبت، 6=الأحد. فارغ = كلّ الأيّام.",
            ),
        ),
    ]
