# Generated by Django 5.2.17 on 2026-09-25 04:01

import ads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0007_servicearea_cancel_driver_late_grace_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='يظهر نصًّا بديلًا وفي التقارير.', max_length=80)),
                ('image', models.FileField(upload_to='ads/%Y/%m/', validators=[ads.models.validate_ad_image])),
                ('placement', models.CharField(choices=[('customer_home', 'رئيسية الزبون (شريط أعلى الخدمات)'), ('trip_finished', 'شاشة انتهاء الرحلة'), ('driver_home', 'رئيسية السائق')], max_length=20)),
                ('link_url', models.CharField(blank=True, help_text='رابط https يفتح خارج التطبيق عند اللمس. فارغ = بلا رابط.', max_length=300)),
                ('service_code', models.CharField(blank=True, help_text='أو خدمة داخل التطبيق (مثال: published_trips) تُفتح عند اللمس.', max_length=40)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='الأصغر أوّلًا.')),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.PositiveIntegerField(default=0, editable=False)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('areas', models.ManyToManyField(blank=True, help_text='فارغ = كلّ المدن.', related_name='ads', to='locations.servicearea')),
            ],
            options={
                'verbose_name': 'إعلان',
                'verbose_name_plural': 'الإعلانات',
                'ordering': ['priority', '-created_at'],
            },
        ),
    ]
