# Generated by Django 5.2.17 on 2026-08-18 22:00

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_driverprofile_verification_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='current_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
