# Generated by Django 5.2.17 on 2026-08-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
