# Generated by Django 5.2.17 on 2026-09-16 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_servicearea_arrival_radius_m_and_more'),
        ('users', '0005_driverprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='home_service_area',
            field=models.ForeignKey(blank=True, help_text='المدينة التي يُدار هذا السائق تحت قواعدها. تُملأ تلقائيًّا عند أوّل اتّصال إن تُركت فارغة.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drivers', to='locations.servicearea'),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='code_salt',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
