# Generated by Django 5.2.17 on 2026-09-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_driverprofile_home_service_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='commission_exempt',
            field=models.BooleanField(default=False, help_text='لا تُخصم منه عمولة المنصّة أبدًا (المؤسّسون).'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='founder_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='رقمه بين المؤسّسين (١–٣٠) كما في ورقة المؤسّس، أو فارغ.', null=True),
        ),
    ]
