# Generated by Django 5.2.17 on 2026-09-20 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_driverprofile_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='first_ride_discount_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to=settings.AUTH_USER_MODEL),
        ),
    ]
