# Generated by Django 5.2.17 on 2026-08-29 08:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_servicearea_allow_renegotiation_after_match_and_more'),
        ('trips', '0001_initial'),
        ('users', '0005_driverprofile_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('fare', 'الأجرة'), ('route', 'المسار'), ('behavior', 'سلوك'), ('safety', 'السلامة'), ('vehicle', 'حالة المركبة'), ('no_show', 'عدم الحضور'), ('lost_item', 'أغراض منسيّة'), ('other', 'أخرى')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('low', 'منخفضة'), ('normal', 'عادية'), ('high', 'مرتفعة'), ('critical', 'حرجة')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_review', 'قيد المراجعة'), ('resolved', 'محلولة'), ('rejected', 'مرفوضة')], db_index=True, default='open', max_length=12)),
                ('description', models.TextField()),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('resolution_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('against_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_received', to=settings.AUTH_USER_MODEL)),
                ('against_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints_received', to='users.driverprofile')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_filed', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_resolved', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity', '-created_at'], name='feedback_co_status_e6cec4_idx'), models.Index(fields=['against_driver', '-created_at'], name='feedback_co_against_ee74b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('c2d', 'الزبون يقيّم السائق'), ('d2c', 'السائق يقيّم الزبون')], db_index=True, max_length=3)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_ratings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_received_or_given', to='users.driverprofile')),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_written', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='trips.trip')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver', 'direction', '-created_at'], name='feedback_ra_driver__76eedc_idx'), models.Index(fields=['customer', 'direction', '-created_at'], name='feedback_ra_custome_1f44ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'direction'), name='unique_rating_per_trip_direction')],
            },
        ),
        migrations.CreateModel(
            name='RatingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('one_star', models.PositiveIntegerField(default=0)),
                ('two_star', models.PositiveIntegerField(default=0)),
                ('three_star', models.PositiveIntegerField(default=0)),
                ('four_star', models.PositiveIntegerField(default=0)),
                ('five_star', models.PositiveIntegerField(default=0)),
                ('recalculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to=settings.AUTH_USER_MODEL)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to='users.driverprofile')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', True), ('driver__isnull', False)), models.Q(('customer__isnull', False), ('driver__isnull', True)), _connector='OR'), name='rating_summary_exactly_one_subject')],
            },
        ),
        migrations.CreateModel(
            name='RatingTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('direction', models.CharField(choices=[('c2d', 'الزبون يقيّم السائق'), ('d2c', 'السائق يقيّم الزبون')], db_index=True, max_length=3)),
                ('polarity', models.CharField(choices=[('positive', 'إيجابي'), ('negative', 'سلبي')], default='positive', max_length=10)),
                ('min_score', models.PositiveSmallIntegerField(default=1)),
                ('max_score', models.PositiveSmallIntegerField(default=5)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service_area', models.ForeignKey(blank=True, help_text='اتركه فارغًا ليظهر الوسم في كل المدن.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_tags', to='locations.servicearea')),
            ],
            options={
                'ordering': ['direction', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('code', 'direction'), name='unique_tag_code_per_direction')],
            },
        ),
    ]
