# Generated by Django 5.2.17 on 2026-08-29 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('release_driver', 'تحرير سائق عالق'), ('force_complete', 'إنهاء رحلة إداريًا'), ('force_cancel', 'إلغاء رحلة إداريًا'), ('verify_driver', 'توثيق سائق'), ('reject_driver', 'رفض سائق'), ('suspend_driver', 'إيقاف سائق')], db_index=True, max_length=20)),
                ('target_type', models.CharField(max_length=30)),
                ('target_id', models.PositiveIntegerField()),
                ('reason', models.TextField()),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='ops_adminac_target__edcea9_idx'), models.Index(fields=['actor', '-created_at'], name='ops_adminac_actor_i_92889e_idx')],
            },
        ),
    ]
