# Generated by Django 5.2.17 on 2026-09-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('ride', 'طلب رحلة'), ('offer', 'عرض سائق'), ('invitation', 'دعوة مباشرة'), ('trip', 'رحلة'), ('payment', 'دفعة'), ('refund', 'استرجاع'), ('driver', 'ملفّ سائق'), ('document', 'وثيقة سائق'), ('shared_join', 'طلب انضمام مشترك'), ('shared_group', 'مجموعة رحلة مشتركة'), ('scheduled_trip', 'رحلة مجدولة مشتركة'), ('vehicle', 'مركبة'), ('user', 'مستخدم'), ('complaint', 'شكوى')], db_index=True, max_length=20)),
                ('entity_id', models.PositiveIntegerField(db_index=True)),
                ('action', models.CharField(choices=[('created', 'أُنشئ'), ('status_changed', 'تغيّرت الحالة'), ('updated', 'عُدِّل'), ('deleted', 'حُذف'), ('admin_action', 'تدخّل إداري'), ('security', 'حدث أمني')], db_index=True, default='status_changed', max_length=20)),
                ('from_state', models.CharField(blank=True, default='', max_length=40)),
                ('to_state', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('actor_label', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('actor_role', models.CharField(blank=True, default='', max_length=20)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-created_at'], name='audit_entity_timeline_idx'), models.Index(fields=['actor_label', '-created_at'], name='audit_actor_idx'), models.Index(fields=['to_state', '-created_at'], name='audit_state_idx')],
            },
        ),
    ]
