# Generated by Django 5.2.17 on 2026-09-19 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyRide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='التاريخ والساعة كما في الدفتر.')),
                ('customer_phone', models.CharField(db_index=True, max_length=20)),
                ('driver_phone', models.CharField(blank=True, db_index=True, max_length=20)),
                ('origin', models.CharField(blank=True, max_length=200, verbose_name='from')),
                ('destination', models.CharField(blank=True, max_length=200, verbose_name='to')),
                ('area', models.CharField(blank=True, help_text='JAB / LAT / OUT', max_length=8)),
                ('offers', models.PositiveSmallIntegerField(default=0, help_text='كم سائقًا عرض')),
                ('price', models.PositiveIntegerField(blank=True, help_text='عدد صحيح بالليرة', null=True)),
                ('minutes_to_offer', models.PositiveSmallIntegerField(blank=True, help_text='كم دقيقة حتّى وصل أوّل عرض', null=True)),
                ('status', models.CharField(choices=[('done', 'تمّ'), ('cancelled', 'ألغيت'), ('unserved', 'لم تُخدَم')], max_length=12)),
                ('fail_reason', models.CharField(blank=True, max_length=200)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_rides_as_customer', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_rides_as_driver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-datetime'],
                'constraints': [models.UniqueConstraint(fields=('datetime', 'customer_phone'), name='legacy_ride_unique_row')],
            },
        ),
    ]
